apiVersion: v1
kind: Service
metadata:
  name: simplenotes-backend 
  labels:
    app: backend 
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      name: http
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}