apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simplenotes-ingress
  annotations:
    # This annotation is important for the NGINX Ingress Controller
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: simplenotes.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
