apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: simplenotes-backend-monitor
  namespace: monitoring 
  labels:
    release: prometheus 
spec:
  selector:
    matchLabels:
      app: backend 
  namespaceSelector:
    matchNames:
      - app
  endpoints:
  - port: http
    interval: 15s