name: Frontend CI/CD

on:
  push:
    branches:
      - master # Or your main branch
    paths:
      - 'frontend/**' # Triggers only on changes in the frontend folder

jobs:
  build:
    name: Build & Test Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Run tests
        working-directory: ./frontend
        run: npm test

  docker:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend 
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/simplenotes-frontend:${{ github.run_id }}

  update-newtag-in-helm:
    name: Update Helm Chart
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GIT_PAT }}

      - name: Update new tag in Helm chart
        run: |
          # This command finds the line with the frontend repository and replaces the tag on the next line
          sed -i '/simplenotes-frontend/!b;n;s/tag: .*/tag: "${{ github.run_id }}"/' helm/simplenotes-app-chart/values.yaml

      - name: Commit and push changes
        run: |
          git config --local user.email "ariefshaik001@gmail.com"
          git config --local user.name "ariefshaik7"
          git add helm/simplenotes-app-chart/values.yaml
          git commit -m "ci: update frontend image tag to ${{ github.run_id }}"
          git push

